// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXiqaD_FcVejYYzi-D0kkKPd9G2W1zvUE',
    appId: '1:160734617668:web:a2b9859a45d1a9316d9c11',
    messagingSenderId: '160734617668',
    projectId: 'sahabatsatwa-app',
    authDomain: 'sahabatsatwa-app.firebaseapp.com',
    storageBucket: 'sahabatsatwa-app.firebasestorage.app',
    measurementId: 'G-98EC0DVPCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiTh-kGq-HvI4yfFWPb6LzAxZBPgvGiKk',
    appId: '1:160734617668:android:7de781ba48030d6b6d9c11',
    messagingSenderId: '160734617668',
    projectId: 'sahabatsatwa-app',
    storageBucket: 'sahabatsatwa-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmTMP_YC_dfKXC3FFqldAr2Oma-vS-k9k',
    appId: '1:160734617668:ios:a3369144fa74bf346d9c11',
    messagingSenderId: '160734617668',
    projectId: 'sahabatsatwa-app',
    storageBucket: 'sahabatsatwa-app.firebasestorage.app',
    iosBundleId: 'com.example.sahabatsatwaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmTMP_YC_dfKXC3FFqldAr2Oma-vS-k9k',
    appId: '1:160734617668:ios:a3369144fa74bf346d9c11',
    messagingSenderId: '160734617668',
    projectId: 'sahabatsatwa-app',
    storageBucket: 'sahabatsatwa-app.firebasestorage.app',
    iosBundleId: 'com.example.sahabatsatwaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXiqaD_FcVejYYzi-D0kkKPd9G2W1zvUE',
    appId: '1:160734617668:web:c9d4afe912e5ef076d9c11',
    messagingSenderId: '160734617668',
    projectId: 'sahabatsatwa-app',
    authDomain: 'sahabatsatwa-app.firebaseapp.com',
    storageBucket: 'sahabatsatwa-app.firebasestorage.app',
    measurementId: 'G-25FPSQHC28',
  );
}
